# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Poppin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Poppin
  pod 'FBSDKLoginKit'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Gifu'
  pod 'Kingfisher', '~> 4.0'	
  pod 'NVActivityIndicatorView' 
  pod 'ObjectMapper', '~> 3.4'  
  pod 'UberRides', '~> 0.11'
end
